<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
    <title><?php echo isset($title_for_layout)?$title_for_layout:'Administration'; ?></title> 

    <!-- LINKS TO LOAD... 
    ======================================================== -->
    <link rel="stylesheet" media="screen"  type="text/css" href="<?php echo Router::webroot('css/font.css'); ?>">
    <link rel="stylesheet" media="screen"  type="text/css" href="<?php echo Router::webroot('css/admin.css'); ?>">
    <link rel="stylesheet" media="screen"  type="text/css" href="<?php echo Router::webroot('css/superfish.css'); ?>">
    <link rel="stylesheet" media="screen"  type="text/css" href="<?php echo Router::webroot('css/superfish-navbar.css'); ?>">    
    <link rel="stylesheet" media="screen"  type="text/css" href="<?php echo Router::webroot('css/jqueryui/jquery-ui-1.8.16.custom.css'); ?>">
    <link rel="stylesheet" media="screen"  type="text/css" href="<?php echo Router::webroot('zoombox/zoombox.css'); ?>"> 
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,800' rel='stylesheet' type='text/css'>

    <style type="text/css">
    /* Generated by Font Squirrel (http://www.fontsquirrel.com) on October 16, 2012 */
    @font-face {
        font-family: 'continuum_mediumregular';
        src: url('<?php echo Router::webroot('font/contm-webfont.eot'); ?>');
        src: url('<?php echo Router::webroot('font/contm-webfont.eot?#iefix'); ?>') format('embedded-opentype'),
             url('<?php echo Router::webroot('font/contm-webfont.woff'); ?>') format('woff'),
             url('<?php echo Router::webroot('font/contm-webfont.ttf'); ?>') format('truetype'),
             url('<?php echo Router::webroot('font/contm-webfont.svg#continuum_mediumregular'); ?>') format('svg');
        font-weight: normal;
        font-style: normal;

    }
    </style>

  </head> 
 
  <body>       

<div id="wrapper">
    <div class="main">
<!--==============================header=================================-->
      <div class="header">
        <div id="logo">
          <h1><a class="logo" href="<?php echo Router::url('admin/posts/welcome'); ?>">MicroWeb</a></h1>
        </div>
        <div id="navi">
          <ul id="sample-menu-1" class="sf-menu sf-navbar">
            <li>
              <a href="<?php echo Router::url('admin/posts/welcome'); ?>">Menu</a>
              <ul>
                <li><a href="<?php echo Router::url('admin/posts/contenu'); ?>">Contenu</a></li>
                <li><a href="<?php echo Router::url('admin/posts/index'); ?>">Articles</a></li>
                <li><a href="<?php echo Router::url('admin/slides/index'); ?>">Slideshow</a></li>          
                <li><a href="<?php echo Router::url('admin/customers/index'); ?>">Client Database</a></li>          
              </ul>
            </li>
            <li><a href="<?php echo Router::url('admin/posts/analytics'); ?>">Statistiques</a></li>
            <li><a href="<?php echo Router::url('admin/parametres/index'); ?>">Configuration</a></li>
            <li><a href="<?php echo Router::url('admin/posts/aide'); ?>">Aide</a></li> 
            <li><a href="<?php echo Router::url(); ?>">Voir le site</a></li> 
            <li><a href="<?php echo Router::url('users/logout'); ?>">Se déconnecter</a></li> 
          </ul>
        </div>
      </div>
<!--==============================End header=============================-->



  <!-- CONTENT
  ======================================================== -->
    <div>
        <?php echo $this->Session->flash(); ?>
        <?php echo stripslashes($content_for_layout); ?>
    </div>

      <div class="boxfooter">
        <div class="center"><b><a href="http://www.micro-web.be/fr" target="_blank">MicroWeb</a></b> - Tous droits réservés 2013 ©.</div>
      </div>

  </div><!-- DIV END 4 class="main" -->

</div><!-- DIV END 4 id="wrapper" -->


<!--==============================footer=================================-->

<!--==============================End footer=================================-->

  </body> 

  <!-- JAVASCRIPT - Placed at the end of the document so the pages load faster
  ============================================================================== -->

  <script type="text/javascript" src="<?php echo Router::webroot('js/jquery-1.9.0.min.js'); ?>"></script>   <!-- JQuery -->
  <script type="text/javascript" src="<?php echo Router::webroot('js/jquery00.js'); ?>"></script>           <!-- Zoombox, DatePicker -->
  <script type="text/javascript" src="<?php echo Router::webroot('js/hoverIntent.js'); ?>"></script>        <!-- Dunno but its 4 Menu BackOff -->
  <script type="text/javascript" src="<?php echo Router::webroot('js/superfish.js'); ?>"></script>          <!-- DUnno but its 4 Menu BackOff -->
  <script type="text/javascript" src="<?php echo Router::webroot('js/bootstrap-collapse.js'); ?>"></script> <!-- Accordion -->

<!-- Permet d'obtenir le plugin de transition d'affichage du menu... -->  
  <script>

    jQuery(document).ready(function(){
      jQuery('ul.sf-menu').superfish({
        pathClass:  'current'
      });
    });

  </script>


<!-- Permet d'obtenir le plugin zoombox... -->  
  <script type="text/javascript" src="<?php echo Router::webroot('zoombox/zoombox.js'); ?>"></script>    
  <script type="text/javascript">
  jQuery(function($){
    $('a.zoombox').zoombox({
        theme : 'zoombox',
        opacity : 0.8
    });
  });
  </script>

<!-- Permet d'obtenir le petit calendrier lors de la selection de la date... -->  
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.js"></script>
  <script type="text/javascript" src="<?php echo Router::webroot('js/datepicker-fr.js'); ?>"></script>
  <script type="text/javascript">
      $(function(){
          $.datepicker.setDefaults( $.datepicker.regional['fr'] ); 
          $( ".datepicker" ).datepicker({
              dateFormat : 'yy-mm-dd'
          });
      })
  </script>

<!-- Permet d'afficher un loader durant l'upload du formulaire... -->  
  <script type="text/javascript">
      function uploading()
      {
          // On cache le contenu de notre page
          $("#content2").hide(); 
          //Show the placeholder div
          document.getElementById("loader2").style.display = "block";
          //Add the loader image to the loader2 div
          document.getElementById("loader2").appendChild(loader2);
      }
  </script>

</html>