<!DOCTYPE html>
<html>
    <head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo isset($title_for_layout)?$title_for_layout:'Poivre et Sel'; ?></title> 
    <meta name="description" content="<?php echo isset($description_for_layout)?$description_for_layout:"Découvrez une cuisine traditionnelle italienne revisitée où les saveurs, la beauté et l'originalité des plats ne laissent personne indifférent !"; ?>">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

    <link rel="stylesheet" href="<?php echo Router::webroot('css/style2.css'); ?>" type="text/css" media="screen" />     
    <link rel="stylesheet" href="<?php echo Router::webroot('zoombox/zoombox.css'); ?>" type="text/css" media="screen" /> 
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans' type='text/css'>


    <style type="text/css">
    /* Generated by Font Squirrel (http://www.fontsquirrel.com) on October 16, 2012 */
    @font-face {
        font-family: 'continuum_mediumregular';
        src: url('<?php echo Router::webroot('font/contm-webfont.eot'); ?>');
        src: url('<?php echo Router::webroot('font/contm-webfont.eot?#iefix'); ?>') format('embedded-opentype'),
             url('<?php echo Router::webroot('font/contm-webfont.woff'); ?>') format('woff'),
             url('<?php echo Router::webroot('font/contm-webfont.ttf'); ?>') format('truetype'),
             url('<?php echo Router::webroot('font/contm-webfont.svg#continuum_mediumregular'); ?>') format('svg');
        font-weight: normal;
        font-style: normal;

    }
    </style>

    </head>

    <body id="top">

<!-- Google Analytics to place juste after the body opening tag--> 
    <?php include_once(CORE.DS."Analyticstracking.php") ?>

<!-- header --> 
    <div id="header">
        <div id="banner_header">
            <a href="<?php WEBROOT; ?>">
                <img src="<?php echo Router::webroot('/img/layout/microweb/logo.png'); ?>" title="Micro-Web" class="imglogo"/>
            </a>
            <!-- réseaux sociaux -->
                <div id="social">
                    <ul>
                    <li><a href="http://www.facebook.com/micro.web.be" title="Nous suivre sur facebook" class="face_ico">facebook</a></li>
                    <li><a href="https://twitter.com/microwebbelgium" title="Nous suivre sur twitter" class="twit_ico">twitter</a></li>
                    <li><a href="#" title="s'abonner aux Flux RSS" class="rss_ico">rss</a></li>
                    <li><a href="mailto:benjamin@micro-web.be" title="Nous Contacter" class="mail_ico">Contact</a></li>
                    </ul>
                    
                </div>
    <?php 

      // Création d'un vecteur de lien contenant les liens hypertextes de mon menu
     $items = array(
         array("link"=>"/fr/", "label"=>"Home"),
         array("link"=>"/fr/actualite", "label"=>"Actualit&eacute;s"),
         array("link"=>"/fr/services", "label"=>"Services"),
         array("link"=>"/fr/valeurs", "label"=>"Valeurs ajoutées"),
         // MENU POUR LE PORTFOLIO 
         // ======================================================
         // array("link"=>"/fr/portfolio", "label"=>"Portfolio"),
         // ======================================================
         array("link"=>"/fr/propos", "label"=>"A propos"),
         array("link"=>"/fr/contact", "label"=>"Contact"));

     $menu = '';

     // Boucle de création de la liste <ul><li>
     foreach ($items as $val) {
         $menu .= '<li><a href="http://www.poivre-et-sel.be'.$val['link'].'"';
         // Vérification si la page X est la page en cours
         // Si oui ajouter la classe « current » à l'élément de la liste
         if ($_SERVER['REQUEST_URI'] == $val['link'])
             $menu .= ' class="current"';
         $menu .= '>'.$val['label'].'</a></li>';
     }



     ?>        
    
<!-- Show Set Flash information -->
                <div>
                    <?php echo $this->Session->flash(); ?>
                </div>


<!-- Menu -->
    <div id="menu02">
          <ul> 
                <?php echo $menu;  ?>
          </ul>
    </div>  
        
<!-- fin du header -->
        </div>
    </div>
 
 <!-- Contenu -->
 <div id="content">
 <div id="contenu_centre">
    <div id="contenu02">
    <?php echo stripslashes($content_for_layout); ?>
</div>
</div>
</div>
        
    </div>          
    <!--footer -->
    <div id="footer">
        <div id="footer02">
                <p><span>Copyright &copy; <?php echo date("Y"); ?> <b>Micro-Web</b>. Tous droits réservés.</span> design by 
                <a href="http://www.micro-web.be" title="Micro-Web.be - Websites for Micro-Entreprises">Micro-Web</a>
        </p>
        </div>
        
    </div>
    
    </body>
  <!-- JAVASCRIPT - Placed at the end of the document so the pages load faster
  ============================================================================= -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>   
    <script type="text/javascript" src="<?php echo Router::webroot('js/portfolio.js'); ?>"></script>    
    <script type="text/javascript" src="<?php echo Router::webroot('js/main.js'); ?>"></script>        
    <script type="text/javascript" src="<?php echo Router::webroot('zoombox/zoombox.js'); ?>"></script>    
</html>
